# Generated by Django 3.2.4 on 2021-07-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('numeroid', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Numero de identificacion')),
                ('foto', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia proveedor')),
                ('nombreComp', models.CharField(max_length=70, verbose_name='Nombre completo')),
                ('Direccion', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.CharField(max_length=20, verbose_name='Correo electronico')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('contrasenna', models.CharField(max_length=8, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('Tipo', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Numero de telefono')),
                ('ttelefono', models.IntegerField(verbose_name='Numero')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroundZero.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idm', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='id moneda')),
                ('moneda', models.CharField(max_length=20, verbose_name='Tipo de moneda')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroundZero.registro')),
            ],
        ),
    ]
